### ISSUE TITLE
No solution for a casual mode seed. (and hard mode too)

### ISSUE THREAD

**Issue by elreymu** [theonlydude/RandomMetroidSolver#2]
I have noticed the solver doesn't take into account the layout changes in casual mode (There are some other changes in normal and tournament aswell in the online randomizer), i got a casual seed that the solver says it has no solution, checked myself in game and noticed there's a change in layout early on that lets the player to access brinstar's power bomb without morph ball. (morph ball was there)
I guess the solver took it as "You need morphball to access morphball".

I am not very concerned about casual mode but considering there's also changes like that in the other modes it would be great if the solver takes into account those changes in the other difficulties aswell. (For the online randomizer)
Here's the seed i used.

Casual mode seed: 4247433
Hard mode seed: 5221591  (This one doesn't have a solution according to the solver either, it's probably because of the same reason, i don't know much about the changes in level design on hard mode so i can't really say much)

(I enabled all of the techniques for both)

**Comment by flohgh** [comment]
I'm not surprised that hard mode does not work since it requires going to lower norfair without Varia. Since the solver is targeted towards a rather "casual" audience, we did not take that into account. Also the solver initially worked only on tournament seeds. We are currently giving access to more advanced settings (hell runs and bosses difficulty) in the web site, so this is the occasion to add a lower norfair "hell run" to be able to solve these seeds.

As for the casual mode in 2.9 version, I was not aware that total added more patches to it. This reveals a wider problem with the solver, because we do not take into account the various patches to the ROMs. This is why open mode seeds are also unsupported (I personally tried 3 open mode seeds and could not finish one so there might be problems in the randomizer itself as well...or I just suck). Anyway thanks for the feedback, I guess we have to find a way to support the various patch sets one way or another.

**Comment by elreymu** [comment]
Thank you for your quick reply, also i have another quetion, does the solver's route only show items that are possible to access in the current area or needed pickups?
It would be cool if it could show the most optimal route without picking up items that are not needed for completion.
For example i got this at the end of a tournament seed on minimal mode:

Screw Attack | LowerNorfair | SpringBall | 1.00 |  
Energy Tank, Firefleas | LowerNorfair | XRayScope | 1.00 |  
Energy Tank, Ridley | LowerNorfair | ETank | 2.69 |  
The End | The End | The End | 1.04

pretty sure spring ball and xray are not needed to finish the game (considering i have space jump at that point) so i am not sure what it means when if it's on minimal, normally i would think i actually need that item.

**Comment by flohgh** [comment]
And I agree that springball and xray do not help lower the difficulty, but once the algorithm decides to go somewhere, it picks up the item to check it off the list of available locations.

**Comment by elreymu** [comment]
Well i tried with hardcore and mania difficulties and it also picks up spring ball and screw attack.
This is the seed i used 9962716 (tournament) if you would like to check it out.

So basically there's no option for a "fastest"/"optimal" route in the solver? or is there? (I thought minimal did that)
Would be very interesting since that would add more techniques to the run if it decides to skip items. (not sure if it already does that to some extend though)

**Comment by flohgh** [comment]
Yeah I kinda did see that coming, that's why I used the verb "should" :)

The navigation algorithm is really dumb for now compared to a human player. We added a few tweaks to avoid unrealistic backtracking, but this is mostly a tool telling you if a seed is finishable, not a "speedrunning simulator". If you are comfortable enough to skip useful items you stumble upon, I guess you don't really need this solver :)

We are working on a much more complex and realistic navigation algorithm, also taking into accout things like general movement difficulty in an area depending on your items, but we're pretty far from getting it done. Though even with this you would not get 'optimal' results in the mathematical sense, but it would certainly take a more realistic path.

**Comment by theonlydude** [comment]
Hello,
We did try to add a super minimal mode for items picking, but he wasn't working, because some roms required to do a sprinball jump and even xray can be required to get out of draygon room when suitless.
But we'll find a solution (maybe remove the unnecessary items once the rom is solved).

For the layout we'll have to detect them and update the locations conditions.
This won't be easy as we have to figure the addresses in the rom to check and the values to check...

**Comment by elreymu** [comment]
Thank you for the explanation, you guys are doing a really impressive work, it really makes me want to play the game more.
Would it be possible to add checkboxes for each item?
Say i wanna skip hijump boots or grapple beam (or any item) and uncheck them from a list, then the solver would make a strategy around that or tell me if the run is not finishable, if it's not much to ask
Maybe it's beyong the scope of the solver but thinking about it it has lots of potential as a tool, it's interesting to see what it comes up with.

**Comment by theonlydude** [comment]
We could definitely add this.

**Comment by flohgh** [comment]
Yep, please create a dedicated issue for this feature.

Also, we made a few changes, if you test your seed again, the path taken should be slightly better. Casual seeds are still unsupported, but it's on the way.

**Comment by elreymu** [comment]
That's awesome!
Thank you, posted the issue separately

**Comment by flohgh** [comment]
OK I close this ticket because we now support various patch sets/seed types (all variants of Total rando, Dessy rando, and vanilla game).

Hard mode seeds are now supported, still largely untested though (first and only seed tested forced us to add two new techniques!).

The ROM type detection is silent for now and based on the file name so keep the seed code in it, but the setting will soon be visible on the site.

We also made further modifications (and bugfixes !) to the navigation algorithm, now it has a "stuff and rush" policy that appears to work quite well (still far from "optimum" of course). If you see excessive backtracking try to raise the difficulty target.

Also, website design is slicker, and we made visible hell run/bosses settings.

Enjoy :)
