### ISSUE TITLE
(Suggestion) Crossover Rando Support

### ISSUE THREAD

**Issue by jet082** [theonlydude/RandomMetroidSolver#28]
This is a crazy suggestion, I am aware, but since it looks like the SMALTTP randomizer has been abandoned(?) and VARIA has substantially more functionality, it would be nice to potentially see some of the same technology used to bring VARIA over.

This is an absurd amount of work and it is probably unfeasible, but we can dream, I suppose.

**Comment by flohgh** [comment]
I don't think SMALTTP has been abandoned, as total is working on a multiworld feature for multiplayer seeds. This feature has been implemented for SM only as well by total. Although from what we could see in terms of gameplay, it is very unlikely the feature will exist in VARIA unless some changes are made to make it, well, fun. I suppose it's better suited to the SMALTTP context rather than just SM.

As for porting VARIA features do SMALTTP, if that's indeed what you're asking : to be brutally honest, we don't care about ALTTP at all, so if it is done at some point, it is not gonna be by us. But both projects being open source, motivated enough people could do it :)

**Comment by Nicholas-Steel** [comment]
You can already choose an assortment of tricks you want to see in a ALttPR seed, if you use the Customizer.  This became possible with the recent v31 release.
