### ISSUE TITLE
Option to turn off basic maneuvers

### ISSUE THREAD

**Issue by Bluiscute** [theonlydude/RandomMetroidSolver#31]
Yeah... I suck...
So I got in a game that requires rising morph.
Yep. I can't.
I can wall jump and shinespark for days, but not that.
It took me 15 minutes to get speed over it.
I also find it really weird that you can't turn it off, otherwise, why is it there? It even has a checkmark!
So, please, fix.

**Comment by elreymu** [comment]
Do you mean jumping and turning into morph ball?
It's actually easier than you think , hold down, then press and hold the jump button while still holding down, then press down again and you will morph in the air, you don't have to press it twice, as long as you are holding down while jumping you can just release it and press it again and it will work.

(I am not behind the randomizer but since that is a very elemental/basic technique it is enabled by default because it would greatly decrease the amount of seeds you can get if disabled, but thats just my guess)

**Comment by Bluiscute** [comment]
Oh, makes sense.
