### ISSUE TITLE
Custom Start Location with Majors or Chozo split

### ISSUE THREAD

**Issue by elreymu** [theonlydude/RandomMetroidSolver#35]
I have noticed that selecting a custom start location forces Full split
i want to enable it to chozo split or major so it's less likely i get major progression items right at the beginning without setting it to slowest progression, also to see what kind of seeds i would be getting in harder presets.
can you enable chozo and major splits for these custom locations aswell?

**Comment by flohgh** [comment]
It's forced to Full, because the first available locations where you'd get your first progression items are minor locations in both those splits.

Examples:
- bubble moutain: the missiles where you get varia
- watering hole: both accassible spots where you have to get morph+grav/hi-jump
- gauntlet: morph in one of the missile spots
- ...

**Comment by elreymu** [comment]
Does that mean that if it wasn't forced to full it could make the randomizer abort?

**Comment by flohgh** [comment]
It would make it abort for sure, yes.

**Comment by flohgh** [comment]
closed because not possible
