### ISSUE TITLE
Bug--Gauntlet Top Start

### ISSUE THREAD

**Issue by Dpants777** [theonlydude/RandomMetroidSolver#69]
From a gauntlet top start, you should not be required to immediately obtain the items from both Crateria Gauntlet right and left.  If this is possible, the difficulty level is certainly not 'green' as the Solver indicates.

VARIA_Randomizer_DBFX2666876940451473506_casual_VARIAble

**Comment by theonlydude** [comment]
hello,

there's a visual cue to do it to be at the center of the crumbling blocks, this way both left and right crumble blocks will disappear, then you stand still and shoot in diagonal bottom right or left while the crumble blocks disappear.
check this stream: https://www.youtube.com/watch?v=WH03sbUopVA

we didn't add a technique just for that because there's no 'technique' in it, but we could add a line or screenshot about it in the help.

**Comment by Dpants777** [comment]
Ah, I see!  Now that I see how it's done, I agree I should have figured it out already. Thanks!

    On Wednesday, December 23, 2020, 3:08:26 AM CST, theonlydude <notifications@github.com> wrote:  
 
 


hello,

there's a visual cue to do it to be at the center of the crumbling blocks, this way both left and right crumble blocks will disappear, then you stand still and shoot in diagonal bottom right or left while the crumble blocks disappear.
check this stream: https://www.youtube.com/watch?v=WH03sbUopVA

we didn't add a technique just for that because there's no 'technique' in it, but we could add a line or screenshot about it in the help.

**Comment by theonlydude** [comment]
screenshot added in the help.
